# Generated by Django 4.1.6 on 2023-06-21 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_categorysubscribers_category_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUsersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='CategorySubscribers',
        ),
        migrations.AddField(
            model_name='subscribeduserscategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
        migrations.AddField(
            model_name='subscribeduserscategory',
            name='subscribed_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='subscribed_users',
            field=models.ManyToManyField(through='news.SubscribedUsersCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
