# Generated by Django 4.1.6 on 2023-06-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_subscribeduserscategory_remove_category_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='postThrough',
            new_name='post',
        ),
    ]
